[mypy]
python_version = 3.13
check_untyped_defs = True
warn_return_any = True

# Libraries without type stubs
[mypy-mne.*]
ignore_missing_imports = True

[mypy-mne_bids.*]
ignore_missing_imports = True

[mypy-asrpy.*]
ignore_missing_imports = True
